analysis/urls.py
from django.urls import path

from .views import AnalysisHomepage, AnalysisIncomeView, AnalysisOutcomeView, CashRowView, BalanceSheetView, StoreInventoryView, product_analysis_view
app_name='analysis'

urlpatterns = [
    path('homepage/', AnalysisHomepage.as_view(), name='homepage'),
    path('products/', product_analysis_view, name="product_analysis"),
    path('incomes/', AnalysisIncomeView.as_view(), name='income_analysis'),
    path('outcomes/', AnalysisOutcomeView.as_view(), name='outcome_analysis'),
    path('cash-row/', CashRowView.as_view(), name='cash_row'),
    path('balance-sheet/', BalanceSheetView.as_view(), name='balance_sheet'),
    path('apografi/', StoreInventoryView.as_view(), name='store_inventory')
    
]

orders/urls.py
from django.urls import path
from .views import *
from .autocomplete import CostumerAutocomplete

app_name = 'orders'

urlpatterns = [
    path('list/', OrderListView.as_view(), name='home'),
    path('detail-view/<int:pk>/', OrderUpdateView.as_view(), name='order_update'),
    path('create/', OrderCreateView.as_view(), name='order_create'),
    path('delete/<int:pk>/', delete_order, name='order_delete'),

    path('payment/list/', PaymentListView.as_view(), name='payment_home'),
    path('payment/detail-view/<int:pk>/', PaymentUpdateView.as_view(), name='payment_update'),
    path('payment/create/', PaymentCreateView.as_view(), name='payment_create'),
    path('payment/<int:pk>/', delete_payment, name='payment_delete'),
    path('coostumer-autocomplete/', CostumerAutocomplete.as_view(), name='costumer_auto'),

    ]

shop_quick_view/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView
)

from analysis.data_views import backup_taxes_view
from costumers.data_views import (backup_invoice_items_view, backup_payments_invoices_view, backup_customers_view,
                                  backup_my_card_view, backup_customers_details_view
                                  )
from frontend.data_views import backup_payment_methods_view
from general_expenses.data_files import backup_general_expenses_folder_view, backup_general_expenses_category_folder_view
from incomes.data_views import backup_incomes_view
from notebook.data_views import backup_notebook_view, backup_tags_view
from orders.data_views import backup_orders_view, backup_orders_payment_view
from payroll.data_views import (backup_payrolls_view, backup_occupation_view, backup_bill_view,
                                backup_bill_categories_view,
                                backup_generic_expenses_category_view,
                                backup_generic_expenses_view,
                                backup_persons_view
                                )
from products.data_views import backup_products_view, backup_products_vendor_view, backup_categories_view
from vendors.data_views import backup_vendors_view, backup_vendor_notes_view, backup_vendor_employers_view, backup_vendor_payments_view, backup_vendor_banking_account_view, backup_invoices_view

urlpatterns = [

    path('backup/generic-expenses/', backup_vendors_view),
    path('backup/payrolls/', backup_vendor_notes_view),
    path('backup/occupation/', backup_vendor_employers_view),
    path('backup/bills/', backup_vendor_payments_view),
    path('backup/bill-categories/', backup_vendor_banking_account_view),
    path('backup/generic-expenses-category/', backup_invoices_view),


    path('admin/', admin.site.urls),
    path('costumers/', include('costumers.urls')),
    path('', include('frontend.urls')),
    path('warehouse/', include('vendors.urls')),
    path('products/', include('products.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('payrolls-and-bills/', include('payroll.urls')),
    path('incomes/', include('incomes.urls')),
    path('analysis/', include('analysis.urls')),
    path('generic-expenses/', include('general_expenses.urls')),
    path('notebook/', include('notebook.urls')),


    # tokens
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    # api
    path('api/', include('frontend.api.urls')),
    path('api/vendors/', include('vendors.api.urls')),


    # backups
    path("backup/taxes-modifier/", backup_taxes_view),

    path("backup/invoice-items/", backup_invoice_items_view),
    path("backup/my-cards/", backup_my_card_view),
    path("backup/customers/", backup_customers_view),
    path("backup/customers-details/", backup_customers_details_view),
    path("backup/payment-invoices/", backup_payments_invoices_view),

    path("backup/folder/general-expenses/", backup_general_expenses_folder_view),
    path("backup/folder/general-expenses-category/", backup_general_expenses_category_folder_view),

    path('backup/incomes/', backup_incomes_view),

    path('backup/tags/', backup_tags_view),
    path('backup/notebooks/', backup_notebook_view),

    path('backup/orders/', backup_orders_view),
    path('backup/orders/payment/', backup_orders_payment_view),

    path('backup/payments-methods/', backup_payment_methods_view),

    path('backup/generic-expenses/', backup_generic_expenses_view),
    path('backup/payrolls/', backup_payrolls_view),
    path('backup/occupation/', backup_occupation_view),
    path('backup/bills/', backup_bill_view),
    path('backup/bill-categories/', backup_bill_categories_view),
    path('backup/generic-expenses-category/', backup_generic_expenses_category_view),
    path('backup/persons/', backup_persons_view),

    path('backup/products/', backup_products_view),
    path('backup/products-vendor/', backup_products_vendor_view),
    path('backup/product-categories/', backup_categories_view),

    path('backup/vendors/', backup_vendors_view),
    path('backup/vendors-notes/', backup_vendor_notes_view),
    path('backup/employers/', backup_vendor_employers_view),
    path('backup/vendor-payments/', backup_vendor_payments_view),
    path('backup/vendor-banking-account/', backup_vendor_banking_account_view),
    path('backup/invoices/', backup_invoices_view),




]

analysis/models.py
from django.db import models
from django.core.exceptions import ValidationError
# Create your models here.


class TaxesModifier(models.Model):
    normal = models.IntegerField(default=80, verbose_name='24%')
    half = models.IntegerField(default=0, verbose_name='13%')
    six = models.IntegerField(default=20, verbose_name='6%')

    def __str__(self):
        return 'Taxes'

    def save(self, *args, **kwargs):
        if not self.pk and TaxesModifier.objects.exists():
            # if you'll not check for self.pk
            # then error will also raised in update of exists model
            raise ValidationError('There is can be only one Taxes instance')
        return super(TaxesModifier, self).save(*args, **kwargs)

analysis/views.py
from django.db.models import Sum, FloatField, F
from django.db.models.functions import TruncMonth
from django.shortcuts import render, reverse, get_object_or_404, redirect
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic import ListView, UpdateView, CreateView, TemplateView, DetailView
from django.utils.decorators import method_decorator
from django.contrib.admin.views.decorators import staff_member_required
from django.conf import settings
from django_tables2 import RequestConfig

from decimal import Decimal
from operator import attrgetter
from itertools import chain

from incomes.models import Income
from products.models import Product, ProductVendor
from payroll.models import Bill, Payroll
from vendors.models import Payment, Invoice, Vendor, InvoiceItem
from costumers.models import InvoiceItem as SellItem
from general_expenses.models import GeneralExpense
from .tools import sort_months
from .models import TaxesModifier


@method_decorator(staff_member_required, name='dispatch')
class AnalysisHomepage(TemplateView):
    template_name = 'analysis/homepage.html'


@staff_member_required
def product_analysis_view(request):
    date_filter = True
    invoice_items = InvoiceItem.filters_data(request, InvoiceItem.objects.all())
    sell_items = SellItem.filters_data(request, SellItem.objects.all())

    invoice_product_buy = invoice_items.values("product__title").annotate(Sum("qty"))
    invoice_product_sell = sell_items.values("product__title").annotate(Sum("qty"))
    context = locals()
    return render(request, 'analysis/analysis_products.html', context)



@method_decorator(staff_member_required, name='dispatch')
class AnalysisIncomeView(ListView):
    model = Income
    template_name = 'analysis/analysis_incomes.html'
    paginate_by = 100

    def get_queryset(self):
        qs = Income.objects.all()
        qs = Income.filters_data(self.request, qs)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        date_filter, currency = True, settings.CURRENCY
        back_url = reverse('analysis:homepage')
        total_z = self.object_list.aggregate(Sum('sum_z'))['sum_z__sum'] if self.object_list.exists() else 0
        total_pos = self.object_list.aggregate(Sum('pos'))['pos__sum'] if self.object_list.exists() else 0
        total_cash = total_z - total_pos
        total_order = self.object_list.aggregate(Sum('order_cost'))[
            'order_cost__sum'] if self.object_list.exists() else 0
        total_6 = self.object_list.aggregate(Sum('taxes_6'))['taxes_6__sum'] if self.object_list.exists() else 0
        total_13 = self.object_list.aggregate(Sum('taxes_13'))['taxes_13__sum'] if self.object_list.exists() else 0
        total_24 = self.object_list.aggregate(Sum('taxes_24'))['taxes_24__sum'] if self.object_list.exists() else 0
        total_taxes = total_6 + total_13 + total_24
        total = self.object_list.aggregate(Sum('value'))['value__sum'] if self.object_list.exists() else 0
        # invoices_per_month = invoices.annotate(month=TruncMonth('date')).values('month').annotate(
        #     total=Sum('final_value')).values('month', 'total').order_by('month')
        analysis_per_month = self.object_list.annotate(month=TruncMonth('date_expired')).values('month').annotate(
            total=Sum('logistic_value')).values('month', 'total').order_by('month')

        analysis_z_per_month = self.object_list.annotate(month=TruncMonth('date_expired')).values('month').annotate(
            total=Sum('sum_z')).values('month', 'total').order_by('month')
        analysis_pos_per_month = self.object_list.annotate(month=TruncMonth('date_expired')).values('month').annotate(
            total=Sum('pos')).values('month', 'total').order_by('month')
        analysis_cash_per_month = self.object_list.annotate(month=TruncMonth('date_expired')).values('month').annotate(
            total=Sum('cash')).values('month', 'total').order_by('month')
        context.update(locals())
        return context


@method_decorator(staff_member_required, name='dispatch')
class AnalysisOutcomeView(TemplateView):
    template_name = 'analysis/analysis_outcome.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        currency = settings.CURRENCY
        back_url = reverse('analysis:homepage')
        date_filter = True
        bills = Bill.filters_data(self.request, Bill.objects.all())
        payrolls = Payroll.filters_data(self.request, Payroll.objects.all())
        invoices = Invoice.filters_data(self.request, Invoice.objects.all())
        generic_expenses = GeneralExpense.filters_data(self.request, GeneralExpense.objects.all())
        generic_expenses_analysis = generic_expenses.values('category__title').annotate(total=Sum('value')).order_by(
            '-total')
        generic_expenses_analysis_per_month = generic_expenses.annotate(month=TruncMonth('date')).values('month'). \
            annotate(total=Sum('value')).values('month', 'total').order_by('month')

        total_bills = bills.aggregate(Sum('final_value'))['final_value__sum'] if bills else 0
        analysis_bills = bills.values('category__title').annotate(total=Sum('final_value')).order_by('-total')
        analysis_bills_per_month = bills.annotate(month=TruncMonth('date_expired')).values('month').annotate(
            total=Sum('final_value')).values('month', 'total').order_by('month')

        total_payroll = payrolls.aggregate(Sum('final_value'))['final_value__sum'] if payrolls else 0
        total_invoices = invoices.aggregate(Sum('final_value'))['final_value__sum'] if invoices else 0
        total_generic = generic_expenses.aggregate(Sum('value'))['value__sum'] if generic_expenses else 0
        total_expenses = total_bills + total_payroll + total_invoices + total_generic
        analysis_invoices = invoices.values('vendor__title').annotate(total=Sum('final_value')).order_by('-total')
        analysis_invoices_per_month = invoices.annotate(month=TruncMonth('date')).values('month').annotate(
            total=Sum('final_value')).values('month', 'total').order_by('month')
        payroll_analysis = payrolls.values('person__title').annotate(total=Sum('final_value')).order_by('-total')
        payroll_analysis_per_month = payrolls.annotate(month=TruncMonth('date_expired')).values('month'). \
            annotate(total=Sum('final_value')).values('month', 'total').order_by('month')

        total_6 = invoices.aggregate(Sum('taxes_6'))['taxes_6__sum'] if invoices.exists() else 0
        total_13 = invoices.aggregate(Sum('taxes_13'))['taxes_13__sum'] if invoices.exists() else 0
        total_24 = invoices.aggregate(Sum('taxes_24'))['taxes_24__sum'] if invoices.exists() else 0
        total_taxes = total_6 + total_13 + total_24

        # get unique months
        months = sort_months([analysis_invoices_per_month, analysis_bills_per_month, payroll_analysis_per_month,
                              generic_expenses_analysis_per_month])

        result_per_months = []
        for month in months:
            data = {
                'month': month,
                'total': 0
            }
            # data['invoice'] = ele['total'] for ele in analysis_invoices_per_month if ele['month'] == month else 0
            for ele in analysis_invoices_per_month:
                if ele['month'] == month:
                    data['invoice'] = ele['total']
                    data['total'] = data['total'] + ele['total']
            for ele in analysis_bills_per_month:
                if ele['month'] == month:
                    data['bills'] = ele['total']
                    data['total'] = data['total'] + ele['total']
            for ele in payroll_analysis_per_month:
                if ele['month'] == month:
                    data['payroll'] = ele['total']
                    data['total'] = data['total'] + ele['total']
            for ele in generic_expenses_analysis_per_month:
                if ele['month'] == month:
                    data['generic'] = ele['total']
                    data['total'] = data['total'] + ele['total']
            data['invoice'] = data['invoice'] if 'invoice' in data.keys() else 0
            data['bills'] = data['bills'] if 'bills' in data.keys() else 0
            data['payroll'] = data['payroll'] if 'payroll' in data.keys() else 0
            data['generic'] = data['generic'] if 'generic' in data.keys() else 0
            result_per_months.append(data)

        context.update(locals())
        return context


@method_decorator(staff_member_required, name='dispatch')
class CashRowView(TemplateView):
    template_name = 'analysis/cash_row.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        currency = settings.CURRENCY
        back_url = reverse('analysis:homepage')
        incomes = Income.filters_data(self.request, Income.objects.all()).order_by('date_expired')
        total_z = incomes.aggregate(Sum('sum_z'))['sum_z__sum'] if incomes.exists() else 0
        total_pos = incomes.aggregate(Sum('pos'))['pos__sum'] if incomes.exists() else 0
        total_cash = total_z - total_pos
        total_order = incomes.aggregate(Sum('order_cost'))['order_cost__sum'] if incomes.exists() else 0
        total = incomes.aggregate(Sum('value'))['value__sum'] if incomes.exists() else 0

        date_filter = True

        # outcomes
        vendor_payments = Payment.filters_data(self.request, Payment.objects.all())
        vendor_payments_total = vendor_payments.aggregate(Sum('value'))['value__sum'] if vendor_payments.exists() else 0

        payrolls = Payroll.filters_data(self.request, Payroll.objects.filter(is_paid=True))
        payrolls_total = payrolls.aggregate(Sum('final_value'))['final_value__sum'] if payrolls.exists() else 0

        bills = Bill.filters_data(self.request, Bill.objects.filter(is_paid=True))

analysis/templates/analysis/analysis_incomes.html
{% extends 'dashboard.html' %}  {% load render_table from django_tables2 %}


{% block content %}
    <div class="content" xmlns="http://www.w3.org/1999/html">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4>Συνολική Εικόνα  ==> <span style="color: green"> {{ total }} {{ currency }} </span></h4>
                        <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                            Filters
                        </a>
                        <a href="{{ request.path }}" class="btn btn-danger">Καθαρισμος</a>
                        <a href="{{ back_url }}" class="btn btn-warning pull-right">Επιστροφη</a>
                    </div>
                    <div class="card-body">
                        <div class="collapse" id="collapseExample">
                            <form method="get" class="form">
                                 <div class="row">
                                      {% include 'filters/my_filters.html' %}
                                 </div>
                                 <button type="submit" class="btn btn-"><i class="fa fa-save"></i> Αποθηκευση </button>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-header">
                <h4 class="card-title">
                    <div class='row'>
                        <div class='col-md-4'>
                            <canvas id="totalChart" width="400" height="400"></canvas>
                        </div>
                         <div class='col-md-8' >
                            <canvas id="lineChart" width="400" height="400"></canvas>
                        </div>
                    </div>
                    
                </h4>
                 
                    
              </div>
              <div class="card-body">
                <div class='row'>
                    <div class='col-6'>
                        <h4>Αναλυση ανα μηνα </h4>
                        <table class='table table-bordered'>
                            <thead>
                                <tr>
                                    <th>Ημερομηνια</th>
                                    <th>Κερδη</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for ele in analysis_per_month %}
                                   <tr>
                                        <td>{{ ele.month.month }}/{{ ele.month.year }}</td>
                                        <td>{{ ele.total }}</td>
                                   </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class='col-6'>
                        <h4>Αναλυση ανα κατηγορια</h4>
                        <table class='table table-bordered'>
                            <thead>
                                <tr>
                                    <th>Ειδος</th>
                                    <th>Κερδη</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td  class="table-info">Συνολο Ζ</td>
                                    <td  class="table-info">{{ total_z }} </td>
                                </tr>
                                <tr>
                                    <td  class="table-warning">Συνολο POS </td>
                                    <td  class="table-warning">{{ total_pos }} </td>
                                </tr>
                                <tr>
                                    <td>Συνολο Τιμολογιων </td>
                                    <td>{{ total_order }} </td>
                                </tr>
                                <tr>
                                    <td>Συνολο Μετρητα </td>
                                    <td class='table-light'>{{ total_cash }}</td>
                                </tr>
                                <tr>
                                    <td class='table-success'>Συνολο</td>
                                    <td class='table-success'>{{ total }}</td>
                                </tr>
                                <tr>
                                    <td class='table-danger'>Συνολο ΦΠΑ 6%</td>
                                    <td class='table-danger'>{{ total_6 }}</td>
                                </tr>
                                <tr>
                                    <td class='table-danger'>Συνολο ΦΠΑ 13%</td>
                                    <td class='table-danger'>{{ total_13 }}</td>
                                </tr>
                                <tr>
                                    <td class='table-danger'>Συνολο ΦΠΑ 24%</td>
                                    <td class='table-danger'>{{ total_24 }}</td>
                                </tr>
                                <tr>
                                    <td class='table-danger'>Συνολο ΦΠΑ</td>
                                    <td class='table-danger'>{{ total_taxes }}</td>
                                </tr>

                            </tbody>
                        </table>
                    </div>
                    
                </div>
                <div class="row">
                    <div class="col-1"></div>
                    <div class="col-10">
                        <h4>Δεδομενα</h4>
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>Ημερομηνια</th>
                                    <th>Ζ Ημερας</th>
                                    <th>POS</th>
                                    <th>Μετρητα</th>
                                    <th>Τιμολογια</th>
                                    <th>Επιπλεον</th>
                                    <th>Λογιστικο Συνολο</th>
                                    <th>Συνολο</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for income in object_list %}
                                    <tr>
                                        <td>{{ income.date_expired }}</td>
                                        <td>{{ income.tag_sum_z }}</td>
                                        <td>{{ income.tag_pos }}</td>
                                        <td>{{ income.tag_cash }}</td>
                                        <td>{{ income.tag_order_cost }}</td>
                                        <td>{{ income.tag_extra }}</td>
                                        <td>{{ income.logistic_value }}</td>
                                        <td>{{ income.tag_value }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="row" id="modal_area">

        </div>
    </div>

{% endblock %}

{% block extra_js %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.bundle.min.js" integrity="sha256-TQq84xX6vkwR0Qs1qH5ADkP+MvH0W+9E7TdHJsoIQiM=" crossorigin="anonymous"></script>
    <script>
var ctx = document.getElementById('totalChart');
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: ['Συνολο', 'Συνολο Ζ', 'Συνολο POS', 'Mετρητα', 'Συνολο Τιμ.'],
        datasets: [{
            label: '# Σε Ευρω',
            data: [{{ total }}, {{ total_z }}, {{ total_pos }}, {{ total_cash }}, {{ total_order }}],
            backgroundColor: [
                'green',
                'blue',
                'red',
                'yellow',
                'purple'
                
            ],
            borderColor: [
                'green',
                'blue',
                'red',
                'yellow',
                'purple'
                
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
});
</script>

<script>
var ctx = document.getElementById('lineChart');
var myChart = new Chart(ctx, {
    type: 'line',

    data: {
        labels: [{% for ele in analysis_per_month %} {% if forloop.last %} '{{ ele.month }}'{% else %} '{{ele.month}}', {% endif %} {% endfor %}],
        datasets: [
            {
				label: 'Εσοδα',
				backgroundColor: 'green',
				borderColor: 'green',
				fill: false,
				data:[{% for ele in analysis_per_month %} {% if forloop.last %} {{ ele.total }}{% else %} {{ele.total}}, {% endif %} {% endfor %}],
			},
            {
				label: 'Ζ Ημερας',
				backgroundColor: 'blue',
				borderColor: 'blue',
				fill: false,
				data:[{% for ele in analysis_z_per_month %} {% if forloop.last %} {{ ele.total }}{% else %} {{ele.total}}, {% endif %} {% endfor %}],
			},
            {
				label: 'POS',
				backgroundColor: 'red',
				borderColor: 'red',
				fill: false,
				data:[{% for ele in analysis_pos_per_month %} {% if forloop.last %} {{ ele.total }}{% else %} {{ele.total}}, {% endif %} {% endfor %}],
			},
            {
				label: 'Μετρητα',
				backgroundColor: 'yellow',
				borderColor: 'yellow',
				fill: false,
				data:[{% for ele in analysis_cash_per_month %} {% if forloop.last %} {{ ele.total }}{% else %} {{ele.total}}, {% endif %} {% endfor %}],
			}
            ]

		},
    options: {
        maintainAspectRatio: false,
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
});
</script>
{% endblock %}

analysis/templates/analysis/homepage.html
{% extends 'dashboard.html' %}

{% block content %}
    <div class="content">
        <div class="row">

            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4>Προϊόντα</h4>
                    </div>
                    <div class="card-body">
                        <a href="{% url 'analysis:product_analysis' %}" class="btn btn-danger">Αναλυση Προϊόντων</a>

                    </div>
                </div>
            </div>

            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4>Εσοδα</h4>
                    </div>
                    <div class="card-body">
                        <a href="{% url 'analysis:income_analysis' %}" class="btn btn-success">Αναλυση Εσοδων</a>
                        <a href="{% url 'analysis:store_inventory' %}" class="btn btn-info pull-right">Απογραφη</a>
                    </div>
                </div>
            </div>

            

            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4>Εξοδα</h4>
                    </div>
                    <div class="card-body">
                        <a href="{% url 'analysis:outcome_analysis' %}" class="btn btn-danger">Αναλυση Εξόδων</a>

                    </div>
                </div>
            </div>

            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4>Ισολογισμος</h4>
                    </div>
                    <div class="card-body">
                        <a href="{% url 'analysis:balance_sheet' %}" class="btn btn-warning">Αναλυση Εσοδων - Εξοδων</a>
                        <a href="{% url 'analysis:cash_row' %}" class="btn btn-info pull-right">Ταμειακη Ροη</a>
                    </div>
                </div>
            </div>
        </div>


    </div>
{% endblock %}

analysis/templates/analysis/store_inventory.html
{% extends 'dashboard.html' %}  {% load render_table from django_tables2 %}


{% block content %}
    <div class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">
                            <h2>Απογραφη</h2>
                            <h4>Συνολο Αποθηκης ==> {{ products_total.total }} €</h4>
                        </div>
                        <div class="card-body">

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            {% for ele in vendor_products %}
                <div class="col-4">
                    <div class="card">
                        <div class="card-header">
                            {% if ele.taxes_modifier == 'b' %} ΦΠΑ 13% {% endif %}
                            {% if  ele.taxes_modifier == 'c' %} ΦΠΑ 24% {% endif %}
                            {% if  ele.taxes_modifier == 'a' %} ΦΠΑ 0% {% endif %}

                        </div>
                        <div class="card-body">
                            ΣΥΝΟΛΟ... {{ ele.total }} €
                        </div>
                    </div>
                </div>
            {% endfor %}
            <div class="col-12">
                <div class="card">
                    <div class="card-header">Κατεβασμα Αρχείου</div>
                    <div class="card-body">
                            <button class="btn btn-info"><i class="fa fa-download"></i> Kατεβασμα.</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}