orders/urls.py
from django.urls import path
from .views import *
from .autocomplete import CostumerAutocomplete

app_name = 'orders'

urlpatterns = [
    path('list/', OrderListView.as_view(), name='home'),
    path('detail-view/<int:pk>/', OrderUpdateView.as_view(), name='order_update'),
    path('create/', OrderCreateView.as_view(), name='order_create'),
    path('delete/<int:pk>/', delete_order, name='order_delete'),

    path('payment/list/', PaymentListView.as_view(), name='payment_home'),
    path('payment/detail-view/<int:pk>/', PaymentUpdateView.as_view(), name='payment_update'),
    path('payment/create/', PaymentCreateView.as_view(), name='payment_create'),
    path('payment/<int:pk>/', delete_payment, name='payment_delete'),
    path('coostumer-autocomplete/', CostumerAutocomplete.as_view(), name='costumer_auto'),

    ]

shop_quick_view/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView
)

from analysis.data_views import backup_taxes_view
from costumers.data_views import (backup_invoice_items_view, backup_payments_invoices_view, backup_customers_view,
                                  backup_my_card_view, backup_customers_details_view
                                  )
from frontend.data_views import backup_payment_methods_view
from general_expenses.data_files import backup_general_expenses_folder_view, backup_general_expenses_category_folder_view
from incomes.data_views import backup_incomes_view
from notebook.data_views import backup_notebook_view, backup_tags_view
from orders.data_views import backup_orders_view, backup_orders_payment_view
from payroll.data_views import (backup_payrolls_view, backup_occupation_view, backup_bill_view,
                                backup_bill_categories_view,
                                backup_generic_expenses_category_view,
                                backup_generic_expenses_view,
                                backup_persons_view
                                )
from products.data_views import backup_products_view, backup_products_vendor_view, backup_categories_view
from vendors.data_views import backup_vendors_view, backup_vendor_notes_view, backup_vendor_employers_view, backup_vendor_payments_view, backup_vendor_banking_account_view, backup_invoices_view

urlpatterns = [

    path('backup/generic-expenses/', backup_vendors_view),
    path('backup/payrolls/', backup_vendor_notes_view),
    path('backup/occupation/', backup_vendor_employers_view),
    path('backup/bills/', backup_vendor_payments_view),
    path('backup/bill-categories/', backup_vendor_banking_account_view),
    path('backup/generic-expenses-category/', backup_invoices_view),


    path('admin/', admin.site.urls),
    path('costumers/', include('costumers.urls')),
    path('', include('frontend.urls')),
    path('warehouse/', include('vendors.urls')),
    path('products/', include('products.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('payrolls-and-bills/', include('payroll.urls')),
    path('incomes/', include('incomes.urls')),
    path('analysis/', include('analysis.urls')),
    path('generic-expenses/', include('general_expenses.urls')),
    path('notebook/', include('notebook.urls')),


    # tokens
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    # api
    path('api/', include('frontend.api.urls')),
    path('api/vendors/', include('vendors.api.urls')),


    # backups
    path("backup/taxes-modifier/", backup_taxes_view),

    path("backup/invoice-items/", backup_invoice_items_view),
    path("backup/my-cards/", backup_my_card_view),
    path("backup/customers/", backup_customers_view),
    path("backup/customers-details/", backup_customers_details_view),
    path("backup/payment-invoices/", backup_payments_invoices_view),

    path("backup/folder/general-expenses/", backup_general_expenses_folder_view),
    path("backup/folder/general-expenses-category/", backup_general_expenses_category_folder_view),

    path('backup/incomes/', backup_incomes_view),

    path('backup/tags/', backup_tags_view),
    path('backup/notebooks/', backup_notebook_view),

    path('backup/orders/', backup_orders_view),
    path('backup/orders/payment/', backup_orders_payment_view),

    path('backup/payments-methods/', backup_payment_methods_view),

    path('backup/generic-expenses/', backup_generic_expenses_view),
    path('backup/payrolls/', backup_payrolls_view),
    path('backup/occupation/', backup_occupation_view),
    path('backup/bills/', backup_bill_view),
    path('backup/bill-categories/', backup_bill_categories_view),
    path('backup/generic-expenses-category/', backup_generic_expenses_category_view),
    path('backup/persons/', backup_persons_view),

    path('backup/products/', backup_products_view),
    path('backup/products-vendor/', backup_products_vendor_view),
    path('backup/product-categories/', backup_categories_view),

    path('backup/vendors/', backup_vendors_view),
    path('backup/vendors-notes/', backup_vendor_notes_view),
    path('backup/employers/', backup_vendor_employers_view),
    path('backup/vendor-payments/', backup_vendor_payments_view),
    path('backup/vendor-banking-account/', backup_vendor_banking_account_view),
    path('backup/invoices/', backup_invoices_view),




]

vendors/api/urls.py
from django.urls import path

from .views import (homepage_vendor_view, VendorListApiView, InvoiceListApiView, VendorDetailApiView,
                    PaymentListCreateApiView, InvoiceRetrieveUpdateDeleteApiView
                    )


app_name = 'api_vendors'

urlpatterns = [
    path('', homepage_vendor_view, name='home'),
    path('list-create/', VendorListApiView.as_view(), name='list'),
    path('detail/<int:pk>/', VendorDetailApiView.as_view(), name='detail'),
    path('invoices/list/', InvoiceListApiView.as_view(), name='invoices'),
    path('invoices/update/<int:pk>/', InvoiceRetrieveUpdateDeleteApiView.as_view(), name='invoice_update'),
    path('payments/list/', PaymentListCreateApiView.as_view(), name='payments')
]

vendors/urls.py
from django.urls import path
from .views import (HomepageView, VendorListView, CreateVendorView, UpdateVendorView, delete_vendor_view,
                    VendorNotesView, delete_note_view, NoteUpdateView, VendorCardView, change_note_status_view,
                    create_costumer_from_vendor_view, PaycheckUpdateView, PaycheckListView, 
                    paycheck_delete_view, paycheck_create_view, print_vendor_view, invoices_vendor_list_view,
                    CreateInvoiceView, InvoiceDetailView, InvoiceListView
                    )

from .action_views import (validate_invoice_form_view, validate_employer_view, validate_order_item_update_view,
                           validate_payment_form_view, validate_invoice_edit_form_view, delete_invoice_view, 
                           delete_payment_view, validate_payment_edit_form_view, validate_employer_edit_view,
                           delete_employer_view, validate_create_banking_account_view, delete_invoice_item_view,
                           validate_edit_banking_account_view, delete_banking_account_view, validate_note_creation_view,
                           validate_product_creation_view, validate_product_edit_view, validate_product_vendor_edit_view,
                           copy_product_to_new_vendor, copy_product_from_vendor_card_view, action_favorite_view,
                           action_form_copy_vendor_product_view, validate_paycheck_form_view, validate_create_invoice_order_item_view,
                           create_product_from_invoice

                           
               )
from .ajax_views import (ajax_invoice_modal_view, ajax_invoice_modal_view, 
                         ajax_employer_edit_modal_view, ajax_banking_account_create_modal_view, ajax_banking_account_edit_modal_view, 
                         ajax_payment_edit_modal_view, ajax_show_product_prices, ajax_calculate_vendors_balance_view, ajax_search_warehouse_view,
                         ajax_edit_product_modal, ajax_product_modal_quick_view, ajax_show_product_analysis_view,
                         ajax_search_products, ajax_add_product_to_category_view, ajax_edit_product_submit_view, create_product_from_category_view,
                         ajax_search_products_warehouse_view, ajax_modify_order_item_modal, ajax_create_product_modal
                         )

from .categories_views import (CategoryListView, CategoryUpdateView, category_delete_view, CategoryCreateView,
                               CategoryCardListView, print_category_products_view
                               )
app_name = 'vendors'


urlpatterns = [
    path('home/', HomepageView.as_view(), name='home'),
    path('list/', VendorListView.as_view(), name='list'),
    path('create/', CreateVendorView.as_view(), name='create'),
    path('update/<int:pk>/', UpdateVendorView.as_view(), name='update'),
    path('delelte/vendor/<int:pk>/', delete_vendor_view, name='delete'),

    # invoices
    path("invoices/list/", InvoiceListView.as_view(), name="invoice_list"),
    path("invoices/vendor/<int:pk>/", invoices_vendor_list_view, name="invoices_vendor"),
    path("invoices/create/<int:pk>/", CreateInvoiceView.as_view(), name="invoice_vendor_create"),
    path('invoice-detail/<int:pk>/', InvoiceDetailView.as_view(), name='invoice_update'),
    path('invoice-delete-<int:pk>/', delete_invoice_view, name='invoice_delete'),
    path('validate-order-item-creation/<int:pk>/', validate_order_item_update_view, name='validate_order_item_update'),
    path('delete-invoice-item/<int:pk>/', delete_invoice_item_view, name='delete_invoice_item'),

    path('validate-order-item_creation/<int:pk>/', validate_create_invoice_order_item_view, name='validate_order_item_creation'),

    path('create-costumer-from-vendor/<int:pk>/', create_costumer_from_vendor_view, name='create_costumer_from_vendor'),
    path('kartela/<int:pk>/', VendorCardView.as_view(), name='vendor_card'),
    path('ajax/kartela/product/<int:pk>/', ajax_show_product_prices, name='ajax_product_price'),
    path('ajax/calculate-vendors-balance/', ajax_calculate_vendors_balance_view, name='ajax_vendors_balance'),
    path('ajax-search-warehouse/<int:pk>/', ajax_search_warehouse_view, name='ajax_search_warehouse'),
    path('ajax/edit-product/<int:pk>/', ajax_edit_product_modal, name='ajax_edit_product'),
    path('action/validate/product-edit/<int:pk>/', validate_product_edit_view, name='validate_product_edit'),
    path('action/validate/product-vendor/<int:pk>/', validate_product_vendor_edit_view, name='validate_product_vendor_edit'),
    path('action/favorite-product/<int:pk>/', action_favorite_view, name='action_favorite_product'), 
    path('ajax/product-modal/quick-view/<int:pk>/', ajax_product_modal_quick_view, name='ajax_product_modal_quick_view'),
    path('copy-product-for=new-vendor/<int:pk>/', copy_product_to_new_vendor, name='copy_product_for_new_vendor'),
    path('copy-product-from-vendor/<int:pk>/<int:dk>/', copy_product_from_vendor_card_view, name='copy_product_from_vendor'),

    path('paycheck/list/', PaycheckListView.as_view(), name='paycheck_list'),
    path('paycheck/create/', paycheck_create_view, name='paycheck_create'),
    path('paycheck/detail/<int:pk>/', PaycheckUpdateView.as_view(), name='paycheck_update'),
    path('paychech/delete/<int:pk>/', paycheck_delete_view, name='paycheck_delete'),
    path('print/vendor/<int:pk>/', print_vendor_view, name='print_vendor_view'),

    #  notes
    path('notes/<int:pk>/', VendorNotesView.as_view(), name='notes'),
    path('notes/validate-creation/<int:pk>/', validate_note_creation_view, name='note_create'),
    path('notes/update/<int:pk>/', NoteUpdateView.as_view(), name='note_update'),
    path('notes/status-update/<int:pk>/', change_note_status_view, name='note_update_status'),
    path('notes/delete/<int:pk>/', delete_note_view, name='note_delete'),
    
    path('actions/validate-invoice-form/<int:pk>/', validate_invoice_form_view, name='validate_invoice_view'),
    path('actions/validate-payment-form/<int:pk>/', validate_payment_form_view, name='validate_payment_view'),
    path('actions/validate-employer-form/<int:pk>/', validate_employer_view, name='validate_employer_view'),
    path('actions/validate-product-creation-view/<int:pk>/', validate_product_creation_view, name='validate_product_creation'),
    path('actions/copy/product-from-vendor-card/<int:pk>/', action_form_copy_vendor_product_view, name='action_copy_product_vendor'),

    path('ajax/invoice-modal/<int:pk>/', ajax_invoice_modal_view, name='ajax_invoice_modal'),
    path('actions/validate-invoice-edit-form/<int:pk>/', validate_invoice_edit_form_view, name='validate_invoice_edit_view'),
    path('actions/invoice-delete/<int:pk>/', delete_invoice_view, name='action_delete_invoice'),

    path('ajax/payment-modal/<int:pk>/', ajax_payment_edit_modal_view, name='ajax_payment_modal'),
    path('actions/validate-payment-edit-form/<int:pk>/', validate_payment_edit_form_view, name='validate_payment_edit_view'),
    path('actions/payment-delete/<int:pk>/', delete_payment_view, name='action_delete_payment'),
    path('actions/paycheck/validate-create/<int:pk>/', validate_paycheck_form_view, name='validate_paycheck_create' ),

    #  employer links
    path('actions/validate-employer-edit-form/<int:pk>/', validate_employer_edit_view, name='validate_employer_edit_view'),
    path('actions/employer-delete/<int:pk>/', delete_employer_view, name='action_delete_employer'),
    path('ajax/employer-modal/<int:pk>/', ajax_employer_edit_modal_view, name='ajax_employer_modal'),

    # banking accounts
    path('ajax/modal/banking-account/<int:pk>/', ajax_banking_account_create_modal_view, name='ajax_create_banking_account'),
    path('ajax/modal/banking-account-edit/<int:pk>/', ajax_banking_account_edit_modal_view, name='ajax_edit_banking_account'),
    path('validate/banking-account-create/<int:pk>/', validate_create_banking_account_view, name='validate_create_banking_account'),
    path('validate/banking_account-edit/<int:pk>/', validate_edit_banking_account_view, name='validate_edit_banking_account'),
    path('banking-account-delete/<int:pk>/', delete_banking_account_view, name='delete_account_banking_view'),

    # categories
    path('categories-list/', CategoryListView.as_view(), name='category_list'),
    path('categories-update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('category/create/', CategoryCreateView.as_view(), name='category_create'),
    path('category/delete/<int:pk>/', category_delete_view, name='category_delete'),
    path('category/card-view/<int:pk>/', CategoryCardListView.as_view(), name='category_card'),
    path('ajax/category/product-analysis/<int:pk>/', ajax_show_product_analysis_view, name='ajax_product_analysis'),
    path('print/category/<int:pk>/', print_category_products_view, name="print_category"),


    # actions

    path("ajax/manipulate-product-category/<int:pk>/<int:dk>/<str:action>/", ajax_add_product_to_category_view,
         name="ajax_manipulate_product_category"),
    path("ajax/edit-product-submit/<int:pk>/<int:dk>/", ajax_edit_product_submit_view, name="edit_product_submit"),
    path("ajax/search-products/<int:pk>/", ajax_search_products, name="products_ajax_search"),
    path("submit/create-products-from-category/<int:pk>/", create_product_from_category_view,
         name="create_product_from_category_view"),

    path('action-create-product-from-invoice/<int:pk>/', create_product_from_invoice, name='create_product_from_invoice'),     

    # ajax
    path('ajax-create-product-from-invoice/<int:pk>/<int:dk>/', ajax_create_product_modal, name='ajax_create_product'),
    path('ajax-modify-order-item-modal/<int:pk>/', ajax_modify_order_item_modal, name='ajax_modify_order_item'),
    path('ware-search-products/<int:pk>/', ajax_search_products_warehouse_view, name='search_products_ware'),



    ]

vendors/templates/categories/card_list.html
{% extends 'dashboard.html' %} {% load render_table from django_tables2 %}

{% block content %}
    <div class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4>{{ category.name }}</h4>
                        <button class="btn btn-primary"
                                type="button"
                                data-toggle="collapse"
                                data-target="#filters"
                                aria-expanded="false"
                                aria-controls="collapseExample"
                        >Filters
                        </button>
                         <a href='{{ back_url }}' class='btn btn-warning pull-right'>Επιστροφη</a>
                        <a href="{{ request.path }}" class="btn btn-danger">Καθαρισμος</a>
                    </div>
                    <div class="card-body">
                        <div class="collapse" id="filters">
                            <form class="form" method="get">
                                <div class="row">
                                    {% include 'filters/my_filters.html' %}
                                </div>
                                <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Αποθηκευση </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="accordion" id="accordionExample">
              <div class="card">
                <div class="card-header" id="headingOne">
                  <h2 class="mb-0">
                    <button class="btn btn-info" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                     ΠΡΟΪΟΝΤΑ ΚΑΤΗΓΟΡΙΑΣ
                    </button>
                  </h2>
                </div>

                <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
                  <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h6>Προϊόντα</h6>
                        <a target="_blank" href="{% url 'vendors:print_category' category.id %}?vendor_name={{ request.GET.vendor_name }}" class="btn btn-info"><i class="fa fa-print"></i> </a>
                    </div>
                    <div class="card-body">
                        <div id="category_products">
                            {% include "categories/ajax/ajax_category_products.html" %}
                        </div>

                    </div>
                </div>
            </div>
                </div>
              </div>
              <div class="card">
                <div class="card-header" id="headingTwo">
                  <h2 class="mb-0">
                    <button class="btn btn-success" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                      ΠΡΟΣΘΗΚΗ ΠΡΟΪΟΝΤΟΣ
                    </button>
                  </h2>
                </div>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                  <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <a href="{% url 'vendors:category_list' %}" class="btn btn-warning">ΕΠΙΣΤΡΟΦΗ</a>
                        <h4>ΠΡΟΪΟΝΤΑ</h4>

                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                            ΔΗΜΙΟΥΡΓΙΑ ΠΡΟΪΟΝΤΟΣ
                        </button>

                        <!-- Modal -->
                        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">ΔΗΜΙΟΥΡΓΙΑ ΠΡΟΪΟΝΤΟΣ</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                </div>
                                <div class="modal-body">
                                    <form method="post" action="{% url 'vendors:create_product_from_category_view' category.id %}">
                                        {% csrf_token %}
                                        {{ create_product }}
                                        <button type="submit" class="btn btn-success"> Save </button>
                                    </form>
                                </div>
                                <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

                                </div>
                            </div>
                            </div>
                        </div>
                        <form>
                            <input data-href="{% url 'vendors:products_ajax_search' category.id %}" name="search_name" type="text" class="form-control search_button" placeholder="Αναζήτηση">
                        </form>
                    </div>
                    <div class="card-body" id="product_container">
                        {% include "categories/ajax/ajax_products_search.html" %}
                    </div>
                </div>
            </div>
                </div>
              </div>

            </div>


        <div class="row">


        </div>

    </div>

    <div id="modal_area"></div>

{% endblock %}

{% block extra_js %}
    <script>
        $('.quick-view').click(function (evt) {
            evt.preventDefault();
            $('#modal_area').empty();
            const myBtn = $(this);
            const url = myBtn.attr('data-href');
            $.ajax({
                method: 'GET',
                url: url,
                dataType: 'json',

                success: function (data) {
                    $('#modal_area').html(data.result);
                    $('#quick_view_modal').modal('show');
                }
            })
        })
    </script>

    <script>

        $(".search_button").keyup(function(evt){
            evt.preventDefault();
            const form_data = $(this);
            const value = form_data.val();
            const url = form_data.attr("data-href");

            $.ajax({
                url: url+ `?search_name=${value}`,
                dataType: "json",

                success: function(data){
                    $("#product_container").html(data.result);
                }
            })
        })


        $(".add_class").click(function(evt){
            evt.preventDefault();
            const btn = $(this);
            const href = btn.attr('data-href');
            $.ajax({
                url: href,
                dataType: "json",
                success: function(data){
                    $("#category_products").html(data.result)
                }
            })

        });


        $(".delete_class").click(function(evt){
            console.log("grg")
            evt.preventDefault();
            const btn = $(this);
            const url = btn.attr("data-href")
            $.ajax({
                url: url,
                dataType: "json",
                success: function(data){
                    $("#category_products").html(data.result)
                }
            })

        })

        $(".edit_class").click(function(evt){
            evt.preventDefault()
            const btn = $(this);
            const url = btn.attr("data-href");
            $("#modal_area").empty();
            $.ajax({
                url: url,
                dataType: "json",
                success: function(data){
                    $("#modal_area").html(data.form_data)
                    $('#editModal').modal('show');

                }
            })
        })
    </script>
{% endblock %}